name: Security audit
on:
  workflow_dispatch: # Manually triggerable
  schedule:
    - cron: '0 0 * * *' # Run daily
  push:
    paths: # Only when these files have changed
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    paths: # Only when these files have changed
      - '**/Cargo.toml'
      - '**/Cargo.lock'
jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Security audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
