name: Security audit

on:
  workflow_dispatch: # Manually triggerable
  schedule:
    - cron: '0 0 * * *' # Run daily
  push:
    branches: [ main ]
    paths: # Only when these files have changed
      - '**/Cargo.toml'
      - '**/Cargo.lock'
  pull_request:
    branches: [ main ]
    paths: # Only when these files have changed
      - '**/Cargo.toml'
      - '**/Cargo.lock'

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  audit:
    runs-on: blaze/ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Security audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
